#ifndef PROTOCOL_H
#define PROTOCOL_H

#include <time.h>

#define MAX_USER 32
#define MAX_DEST 32
#define MAX_MSG 512

/*
Protocol notes:

MSG_TEXT:
- destination = room name
- message = room chat text

MSG_DM:
- destination = target username
- message = private message text

MSG_JOIN:
- destination = room name
- message = optional / empty

MSG_LEAVE:
- destination = room name
- message = optional / empty

MSG_NICK:
- destination = empty
- message = requested nickname

MSG_WHO:
- destination = optional / empty
- message = empty

MSG_LIST:
- destination = empty
- message = empty

MSG_QUIT:
- destination = empty
- message = empty

MSG_SYSTEM / MSG_ERROR:
- generated by server
- destination = optional
- message = info / error text
*/

typedef enum {
    MSG_TEXT,
    MSG_DM,
    MSG_JOIN,
    MSG_LEAVE,
    MSG_NICK,
    MSG_WHO,
    MSG_LIST,
    MSG_QUIT,
    MSG_SYSTEM,
    MSG_ERROR
} MessageType;

typedef struct {
    MessageType type;
    char usrid[MAX_USER];
    char destination[MAX_DEST];
    char message[MAX_MSG];
    time_t timestamp;
} Packet;

/* send / receive helpers */
int send_packet(int fd, const Packet *pkt);
int recv_packet(int fd, Packet *pkt);

/* packet helpers */
void init_packet(Packet *pkt);
void print_packet(const Packet *pkt);

/* validation helpers */
int valid_packet_type(MessageType type);
int validate_packet(const Packet *pkt);

#endif